extends QAScript
## QA (spec §16 M14): balancing pass. Boss-sim every boss at its home tiers
## with the QA bot, log time-to-kill and hits-to-kill against §11.6, and write
## the table to docs/BALANCE.md (and user:// when res:// is read-only).
## Targets: mini 2.5–4 min, King 4–6 min, boss kills you in 4–6 hits.

const TARGET_MIN: Dictionary = {"mini": [150.0, 240.0], "king": [240.0, 360.0]}


func tiers_for(kind: String) -> Array[int]:
	match kind:
		"landmark":
			return [6]
		"final", "superboss":
			return [7]
	return [1, 3, 5]


func run() -> bool:
	await frames(2)
	var ids: Array = DataDB.catalog("bosses").keys()
	ids.sort()
	var rows: PackedStringArray = PackedStringArray()
	var in_band: int = 0
	var total: int = 0
	for id: Variant in ids:
		var kind: String = JU.s(DataDB.boss(str(id)), "kind")
		for t: int in tiers_for(kind):
			var r: Dictionary = BossSim.run(str(id), t, {"god": true, "max_s": 900, "seed": 2})
			var ttk: float = float(r["time_s"])
			var band: Array = TARGET_MIN.get("king" if kind != "mini" else "mini", [0.0, 0.0])
			var htk: float = float(r["hits_to_kill"])
			var ok: bool = str(r["result"]) == "victory" and ttk >= float(band[0]) * 0.5 and ttk <= float(band[1]) * 1.5
			total += 1
			in_band += 1 if ok else 0
			var row: String = "| %s | %s | T%d | %s | %.0f s | %d–%d s | %.1f | %d | %s |" % [id, kind, t, r["result"], ttk,
				int(band[0]), int(band[1]), htk, int((r["stats"] as Dictionary)["makes"]), "ok" if ok else "REVIEW"]
			rows.append(row)
			print("QA balance " + row)
			if not check(str(r["result"]) == "victory", "%s T%d: bot did not win (%s)" % [id, t, r["result"]]):
				return false
	_write(rows, in_band, total)
	print("QA balance: %d/%d sims inside 0.5x–1.5x of the §11.6 window" % [in_band, total])
	return check(in_band * 2 >= total, "fewer than half the sims are near the §11.6 windows")


func _write(rows: PackedStringArray, in_band: int, total: int) -> void:
	var md: PackedStringArray = PackedStringArray([
		"# Balance report (spec §11.6, §16 M14)", "",
		"Generated by `tests/qa/qa_balance.gd` (`$GODOT --headless --path . -- --qa-run=balance`).",
		"QA bot (skill tier 6, seed 2, god mode so time-to-kill is measured to the end).",
		"TTK target: mini 2.5–4 min, King/landmark/final 4–6 min. Hits-to-kill: clean boss hits needed",
		"to empty a base-stat (level 1, no gear) player's HP; §11.6's 4–6 assumes a tier-appropriate build,",
		"so low values at T5+ are expected here. `REVIEW` = outside 0.5x–1.5x of the window;",
		"the bot is not a human, so these flag outliers for hands-on tuning rather than fail the build.", "",
		"| Boss | Kind | Tier | Result | TTK | Target | Hits to kill you | Makes | Status |",
		"| --- | --- | --- | --- | --- | --- | --- | --- | --- |"])
	md.append_array(rows)
	md.append("")
	md.append("%d/%d sims inside 0.5x–1.5x of the target window." % [in_band, total])
	var text: String = "\n".join(md) + "\n"
	for path: String in ["res://docs/BALANCE.md", "user://BALANCE.md"]:
		var f: FileAccess = FileAccess.open(path, FileAccess.WRITE)
		if f != null:
			f.store_string(text)
			f.close()
			return
